    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag and Push Image
      run: |
        docker tag sentiment-analysis ${{ secrets.DOCKER_USERNAME }}/sentiment-analysis:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/sentiment-analysis:latest
